### ISSUE TITLE
The markup is broken, highlighting will be wrong.

### ISSUE THREAD

**Issue by a-kempka** [gjb2048/moodle-filter_synhi#11]
**Describe the bug**
In the admin settings (/admin/settings.php?section=filter_synhi_settings) the preview is broken and the error message "The markup is broken, highlighting will be wrong." is displayed

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to version 39.1.0 (2020073106)
2. Go to admin settings (/admin/settings.php?section=filter_synhi_settings)

**Expected behaviour**
a working preview using any engine

**Screenshots**
![image](https://user-images.githubusercontent.com/53858701/230382448-1d3fa65c-26fd-46d6-955c-4ac086684304.png)

**Versions (please complete the following information):**
 - Moodle: 4.1.1 or 3.11
 - Filter: 39.1.0
 - Browser and version: Edge Version 111.0.1661.54 (Official build) (64-bit) on Ubuntu 22.04 LTS

**Comment by gjb2048** [comment]
@a-kempka As you've upgraded, your 'codeexample' setting is using the old default, please set it to the new one.  There was no code logic that I could think of in the upgrade process to make this happen automatically.
