### ISSUE TITLE
non latin characters before the code block break highlighting

### ISSUE THREAD

**Issue by a-kempka** [gjb2048/moodle-filter_synhi#12]
**Describe the bug**
using non latin characters such as ä ö ü ß breaks code highlighting

**To Reproduce**
Steps to reproduce the behaviour:
1. create label with the following HTML
```
<h3>Umlaut breaks highlighting</h3>
<p>code highlighting breaks when using non latin characters: ä ü ß ö - each character cuts makes one char of the not to be highlichted code tag appear</p>
<pre><code>
# This is a Python program that calculates the sum of two numbers
num1 = 5
num2 = 10
sum = num1 + num2
print("The sum of", num1, "and", num2, "is:", sum)
</code>
</pre>
```
The code and pre tag are highlighted as well. The more umlauts you insert, the more characters of the parts after the code are displayed, i.e. the closing tags (code and pre) are highlighted and break the subsequent HTML.

**Expected behaviour**
The code highlighting should end at "sum)"

**Screenshots**
![image](https://user-images.githubusercontent.com/53858701/230385841-3837aa1d-af99-4fac-a106-1a0147306d23.png)

**Versions (please complete the following information):**
 - Moodle: 4.1.1 and 3.11
 - Filter: 39.1.0
 - Browser: Edge Version 111.0.1661.54 (Official build) (64-bit) on Ubuntu 22.04 LTS

**Comment by gjb2048** [comment]
@a-kempka Thanks for the report, please apply https://github.com/gjb2048/moodle-filter_synhi/commit/c4947181dab95e6705ce06da16d070053c85a1d5 and confirm it fixes it for you.

**Comment by gjb2048** [comment]
Release https://moodle.org/plugins/filter_synhi/39.1.1/28905

**Comment by a-kempka** [comment]
Thank you for the quick fix. Umlauts don't interfere with SynHi now.

**Comment by gjb2048** [comment]
@a-kempka Thanks for letting me know.
